REM bin\runner --gtest_filter=-StringTests.* --gtest_output="xml:xml/test_results.xml"
bin\runner --gtest_filter=JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingEmptyObject^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingDoubleValue^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingLiteralTrueValue^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingLiteralFalseValue^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingLiteralNullValue^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingStringValue^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingArrayValueWithNoElements^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingArrayValueWithOneElement^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingArrayValueWithMultipleElements^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingObjectValueWithNoMembers^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingObjectValueWithOneMember^
:JsonDocTests.WhenInitializingDocWithStringThenConvertingDocToJsonExpectStringContainingObjectValueWithMultipleMembers
